server:
  port: 8081
spring:
  application:
    name: edu
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-eyi7qlee.sql.tencentcdb.com:28074/education?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: GcI^7jO$TuxqQ5oqcT(
  redis:
    host: r-2vcx0znxz7wacxuwpqpd.redis.cn-chengdu.rds.aliyuncs.com
    port: 2748
    password: +@IK_1S%Mq*)o!E9
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.edu.entity # 别名扫描包
logging:
  level:
    com.edu: debug
